query getClient($id: String!) {
    client (id: $id){
        id
        name
        companyCategory {
            id
            name
        }
        address
        city
        state {
            id
            name
            abbreviation
        }
        zipcode
        phone
        fax
        websiteUrl
    }
}