query clientSearch($name: String!) {
    clientSearch (name: $name){
        id
        name
        companyCategory {
            id
            name
        }
        address
        city
        state {
            id
            name
            abbreviation
        }
        zipcode
        phone
        fax
        websiteUrl
    }
}